---
title: "Reproducibility Report for 'A dual-pathway architecture for stress to disrupt agency and promote habit' by Giovanniello et al. (2025, Nature)"
author: "Tristan David"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

The experiment I will simulate and reproduce comes from a paper investigating how different nuclei of the amygdala, and their projections to the striatum, support either action-outcome learning or habit formation and its disruption by stress. Chronic, mild stress causes perturbations to these brain regions which can render a mouse unable to employ volitional control over decision-making as evidenced by two gold standard assessments of goal-directed behavior: outcome-devaluation and contingency degradation. The experiments described by this paper are important for questions I want to investigate in my research program because it is one of a few papers examining the projections of CeA-DMS. The DMS is a nucleus within the basal ganglia that has a role in the acquisition of goal-directed behavior that supports adaptive decision-making. The CeA is a nucleus within the amygdalar complex that has become a popular region to investigate its role in incentive motivation. These regions, when investigated on their own, are compromised in disease states such as ethanol dependence and investigating amygdalar-striatal afferents will provide knowledge on neural dysfunction of motivational and cognitive control over decision-making.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Justification for choice of study

Please describe why you chose to reproduce the results of this study.

### Anticipated challenges

Do you anticipate running into any challenges when attempting to reproduce these result(s)? If so please, list them here.

### Links

Project repository (on Github): 

Original paper (as hosted in your repo): 

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study. 

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
